---
name: Nix Flake Check

on:  # yamllint disable-line rule:truthy
  push:

jobs:
  nix-flake-check:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - run: nix flake check
